{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE OverloadedStrings #-}

module Tikka (parseAndEvaluateProject, Flags (..), Parser, lexeme, isFunction, addToLocalDecl) where

import Text.Megaparsec
import Text.Megaparsec.Char
import Prelude hiding (GT, LT)

import Control.Monad
import Control.Monad.Writer.Lazy (Writer, runWriter, tell)

import Control.Exception qualified as E
import Data.Char (isSpace)
import Data.Either (fromLeft, fromRight, isLeft)
import Data.List (dropWhileEnd, intercalate, isInfixOf)
import Data.List.NonEmpty qualified as N
import Data.List.Split (splitOn)
import Data.Ord (clamp)
import Data.Set (difference, fromList, insert, member)
import Data.Text (Text, pack, replace, strip, unpack)
import Data.Text.Internal.Search (indices)
import System.IO.Error (isDoesNotExistError)
import System.IO.Strict qualified as S

import Tikka.Eval
import Tikka.Expr
import Tikka.Parse.Expr
import Tikka.Parse.Helpers

instance ShowErrorComponent String where
  showErrorComponent = id
  errorComponentLen = length

-- Represents each flag which could be passed into the interpreter
data Flags = Flags
  { tracing :: Int
  , verbosity :: Int
  , dump :: String
  , stc :: Bool
  , visual :: Bool
  , repl :: Bool
  }
  deriving (Show)

-- Parses the given file (and it's imports) with the given flags, and either returns a parse error or (Text to dump, Text to output, Type + other errors)
parseAndEvaluateProject :: Flags -> String -> String -> IO (Either String (String, [String], String))
parseAndEvaluateProject flags file func = case parse getImports "" (pack file) of
  Left bundle -> pure (Left $ removeFirstFour $ errorBundlePretty bundle)
  Right (rest, fileNames) -> do
    files <- E.try (readFiles fileNames) :: IO (Either E.IOException [String])
    case files of
      Left err -> if isDoesNotExistError err then (pure . Left) $ "Error: The file/path '" ++ removeLastFour (head $ words $ show err) ++ "' does not exist, so could not be imported" else (pure . Left) $ "Error: " ++ show err
      Right fullFiles -> do
        let concatFile = rest ++ "\n" ++ Data.List.intercalate "\n" fullFiles
        case parseAndEvaluate flags concatFile func of
          Left s -> pure (Left $ removeFirstFour s)
          Right eval -> pure $ Right eval

-- removes the superfluous stack trace in error messages generated by MegaParsec
removeFirstFour :: String -> String
removeFirstFour s = if length (Prelude.lines s) > 4 then Prelude.unlines $ tail $ tail $ tail $ tail $ Prelude.lines s else s

removeLastFour :: [a] -> [a]
removeLastFour xs = take (length xs - 4) xs

-- Parses all import statements in the file
getImports :: Parser (String, [String])
getImports = do
  files <- many getImport
  file <- takeRest
  pure (unpack file, files ++ ["imports/command-line", "imports/local-decl", "imports/prelude"])

-- Parses an import statement
getImport :: Parser String
getImport = do
  lexeme "import"
  lexeme $ many $ noneOf [' ', '\n', '\r']

-- Reads all imported files
readFiles :: [String] -> IO [String]
readFiles [] = pure []
readFiles (x : xs) = do
  original <- E.try (readFile x) :: IO (Either E.IOException String)
  case original of
    Left _ -> do
      first <- readFile $ x ++ ".hs"
      rest <- readFiles xs
      pure (first : rest)
    Right first -> do
      rest <- readFiles xs
      pure (first : rest)

addToLocalDecl :: String -> IO ()
addToLocalDecl s = do
  file <- S.readFile "imports/local-decl"
  let toWrite = addDecl s (Prelude.lines file)
  writeFile "imports/local-decl" (Prelude.unlines toWrite)

addDecl :: String -> [String] -> [String]
addDecl s [] = [s ++ "\n"]
addDecl s (l : ls) = if strip (pack $ head $ splitOn "=" s) == strip (pack $ head $ splitOn "=" l) then s : tryTail ls else l : addDecl s ls
 where
  tryTail [] = []
  tryTail ls' = tail ls'

-- Parses the given file with the given flags, and either returns a parse error or (Text to dump, Text to output, Type + other errors)
parseAndEvaluate :: Flags -> String -> String -> Either String (String, [String], String)
parseAndEvaluate flags file func = case parseFile file func (stc flags) of
  Left s -> if clamp (1, 4) (verbosity flags) > 2 then Left s else Left $ printParseError (lines s)
  Right (evalSteps, errors, deSugared) -> do
    let t = clamp (1, 4) (tracing flags)
    let v = clamp (1, 4) (verbosity flags)
    let toPrint = if isTrace then outputTrace evalSteps t v func else output evalSteps t v func
    if stc flags
      then
        ( do
            let toDump = Data.List.intercalate "\n\n" (map dumpFileSTC (reverse deSugared)) ++ "\n"
            Right (toDump, toPrint, typeCheck v (last evalSteps) ++ printErrors v errors)
        )
      else
        ( do
            let toDump = Data.List.intercalate "\n\n" (map dumpFile (reverse deSugared)) ++ "\n"
            Right (toDump, toPrint, typeCheck v (last evalSteps) ++ printErrors v errors)
        )
 where
  printParseError [err] = err
  printParseError errLines = intercalate "\n" (init errLines) ++ "\n"
  dumpFile ("Just", body, _) = "\n\n-- IMPORTED FROM PRELUDE:\n\nJust = " ++ show body
  dumpFile (name, body, _) = name ++ " = " ++ show body
  dumpFileSTC ("Just", body, signature) = "\n\n-- IMPORTED FROM PRELUDE:\n\nJust :: " ++ show signature ++ "\n" ++ "Just = " ++ show body
  dumpFileSTC (name, body, signature) = name ++ " :: " ++ show signature ++ "\n" ++ name ++ " = " ++ show body
  isTrace = isInfixOf " TRACE " file || isInfixOf "(TRACE " file || isInfixOf " TRACE{" file || isInfixOf " TRACE(" file || isInfixOf "(TRACE(" file || isInfixOf "(TRACE{" file

-- Checks to see if the returned lambda was complete, and if not, type checks the lambda to determine the reason
typeCheck :: Int -> Term -> String
typeCheck _ (Exp _) = ""
typeCheck 3 (Abs _ _) = "Warning: The program is incomplete, as the final result is a function which requires an argument but does not have one\n         This was likely caused by too few arguments being given to one or more functions\n\n"
typeCheck _ (Abs _ _) = "Warning: The program is incomplete, as the final result is a function which requires an argument but does not have one\n\n"
typeCheck 3 (App f g) = "Error: The expression '" ++ show f ++ "' does not take any arguments, yet '" ++ show g ++ "' is applied to it\n       This was likely caused by too many arguments being given to one or more functions\n\n"
typeCheck _ (App f g) = "Error: The expression '" ++ show f ++ "' does not take any arguments, yet '" ++ show g ++ "' is applied to it\n\n"
typeCheck _ (Trace _) = ""

-- Pretty prints any errors encountered, at the given verbosity
printErrors :: Int -> [String] -> String
printErrors _ [] = ""
printErrors 3 (e : es) = e ++ "\n\n" ++ printErrors 3 es
printErrors 4 (e : es) = e ++ "\n\n" ++ printErrors 4 es
printErrors v (e : es) = head (lines e) ++ "\n\n" ++ printErrors v es

-- Parses a given file, returning either an error msg, or a list of lambdas showing the evaluation, any errors and the desugared list of functions
parseFile :: String -> String -> Bool -> Either String ([Term], [String], [(String, Term, TermType)])
parseFile file func True = do
  -- With static type checking
  case parse (program func <* eof) "" (pack file) of
    Left bundle -> Left (errorBundlePretty (clean bundle))
    Right (e, es) -> do
      let funcTypes = map (uncurry (inferTermType es) . (\(s, f) -> ([s], f))) es
      let allGood = checkTypes funcTypes
      when (isLeft allGood) (Left (fromLeft "" allGood))
      let ((_, errors), ls) = runWriter $ simplifyTerm es e (Exp (Var "x"))
      Right (ls, errors, addTypeSigs es (fromRight [] allGood))
parseFile file func False = do
  -- Without static type checking
  case parse (program func <* eof) "" (pack file) of
    Left bundle -> Left (errorBundlePretty (clean bundle))
    Right (e, es) -> do
      let ((_, errors), ls) = runWriter $ simplifyTerm es e (Exp (Var "x"))
      Right (ls, errors, addTypeSigs es [])

clean :: ParseErrorBundle Text String -> ParseErrorBundle Text String
clean (ParseErrorBundle es s) = ParseErrorBundle (N.map cleanError es) s

cleanError :: ParseError Text String -> ParseError Text String
cleanError (TrivialError x m es)
  | member (Tokens (N.fromList "*")) es = TrivialError x m (insert (Label (N.fromList "an operator")) $ difference es $ fromList [Tokens (N.fromList "ceiling"), Tokens (N.fromList "floor"), Tokens (N.fromList "*"), Tokens (N.fromList "/"), Tokens (N.fromList "+"), Tokens (N.fromList "-"), Tokens (N.fromList ":"), Tokens (N.fromList "++"), Tokens (N.fromList "=="), Tokens (N.fromList "/="), Tokens (N.fromList "<"), Tokens (N.fromList "<="), Tokens (N.fromList ">"), Tokens (N.fromList ">="), Tokens (N.fromList "&&"), Tokens (N.fromList "||"), Tokens (N.fromList "$")])
  | otherwise = TrivialError x m es
cleanError e = e

-- Repeatedly evaluate a given lambda, step by step, until the lambda no longer changes. Returns the list of Terms and the final lambda evaluation in a Writer.
simplifyTerm :: LUT Term -> Term -> Term -> Writer [Term] (Term, [String])
simplifyTerm _ (Exp (Val (InfiniteList l))) _ = tell [Exp (Val (InfiniteList l))] >> pure (Exp (Val (InfiniteList l)), []) -- this avoids lazy / infinite lists causing crashing when output
simplifyTerm s f g =
  if f == g
    then pure (f, [])
    else do
      tell [f]
      case evalTerm s f of
        Left errors -> pure (f, errors)
        Right e -> simplifyTerm s e f

-- Print the given evaluation steps
-- 1st arg = evaluation steps
-- 2nd arg = 'trace' flag
-- 3rd arg = 'verbosity' flag
output :: [Term] -> Int -> Int -> String -> [String]
output ls 1 _ _ = [show $ last ls]
output ls t v "main" = ("main " ++ head (steps t v ls)) : tail (steps t v ls)
output ls t v _ = steps t v ls

-- Gets the list of evaluation steps and evaluation
-- 1st arg = 'trace' flag
-- 2nd arg = 'verbosity' flag
-- 3rd arg = evaluation steps
steps :: Int -> Int -> [Term] -> [String]
steps t v ls = map fst (mapSteps t v ls True)

-- Gets all evaluation steps
-- 1st arg = 'trace' flag
-- 2nd arg = 'verbosity' flag
-- 3rd arg = evaluation steps
-- 4th arg = bool stating whether the previous step was visible
mapSteps :: Int -> Int -> [Term] -> Bool -> [(String, Bool)]
mapSteps _ _ [] _ = []
mapSteps t v (l:ls) vis
  | vis && not doprint = (fst eval ++ "    [...]", snd eval) : mapSteps t v ls doprint
  | doprint = eval : mapSteps t v ls doprint
  | otherwise = mapSteps t v ls doprint
    where
      (eval, doprint) = outputEvaluation t v l

-- Print the given evaluation steps inside trace blocks
-- 1st arg = evaluation steps
-- 2nd arg = 'trace' flag
-- 3rd arg = 'verbosity' flag
outputTrace :: [Term] -> Int -> Int -> String -> [String]
outputTrace ls 1 _ _ = [show $ last ls]
outputTrace ls t v "main" = ("main " ++ head (steps' t v ls)) : tail (steps' t v ls)
outputTrace ls t v _ = steps t v ls -- TRACE blocks do not stop trace for repl

-- Gets the list of evaluation steps and evaluation, if inside of a TRACE block
-- 1st arg = 'trace' flag
-- 2nd arg = 'verbosity' flag
-- 3rd arg = evaluation steps
steps' :: Int -> Int -> [Term] -> [String]
steps' t v [l] = [fst $ fst $ outputEvaluation t v l]
steps' t v ls = map fst (filter snd (mapSteps t v (init ls) True)) ++ [fst $ fst $ outputEvaluation t v (last ls)]

-- Outputs one step of evaluation
-- 1st arg = 'trace' flag
-- 2nd arg = 'verbosity' flag
-- 3rd arg = evaluation step
outputEvaluation :: Int -> Int -> Term -> ((String, Bool), Bool)
outputEvaluation t v l = (("= " ++ show l ++ expl, snd action), doprint)
  where
    action = nextAction l t v False
    doprint = fst action /= "noprint"
    expl = if v == 1 || not doprint then "" else fst action

-- Determine the explanation that should be given for a lambda evaluation step
-- 1st arg = evaluation step
-- 2nd arg = 'trace' flag
-- 3rd arg = 'verbosity' flag
-- 4th arg = bool to denote if we are currently inside a TRACE block
nextAction :: Term -> Int -> Int -> Bool -> (String, Bool)
nextAction (Exp e) t v b = nextActionExpr e t v b
nextAction (App (Abs x f) g) _ v b = case v of
  2 -> ("    [Beta Reduction]", b)
  3 -> ("    [Replacement of " ++ x ++ " in " ++ show f ++ " with " ++ show g ++ "]", b)
  _ -> ("    [I will replace all free occurrences of " ++ x ++ " in " ++ show f ++ " with " ++ show g ++ "]", b)
nextAction (App f _) t v b = nextAction f t v b
nextAction (Trace f) t v _ = if fst (nextAction f t 3 True) == "" then ("noprint", False) else nextAction f t v True -- don't print if no evaluation happens inside of the TRACE block
nextAction _ _ _ b = ("", b) -- if this happens, program was not complete

-- Determine the explanation that should be given for an expression evaluation step
-- 1st arg = evaluation step
-- 2nd arg = 'trace' flag
-- 3rd arg = 'verbosity' flag
-- 4th arg = bool to denote if we are currently inside a TRACE block
nextActionExpr :: Expr -> Int -> Int -> Bool -> (String, Bool)
nextActionExpr (Var var) _ v b = case v of
  2 -> ("    [Function Replacement]", b)
  3 -> ("    [Replacement of identifier '" ++ var ++ "' with its function body]", b)
  _ -> ("    [I will replace the function identifier '" ++ var ++ "' with its function body]", b)
-- nextActionExpr (Function l) t v b = nextAction l t v b
nextActionExpr (Val x) t v b = nextActionVal x t v b
nextActionExpr (Error _) _ _ _ = ("", False)
nextActionExpr (UnOp Negation (Exp (Var _))) _ _ _ = ("noprint", False) -- negation function does not need an eval step
nextActionExpr (UnOp Negation (Exp (Val _))) _ _ _ = ("noprint", False) -- negation function does not need an eval step
nextActionExpr (UnOp Negation e) t v b = nextAction e t v b
nextActionExpr (UnOp Floor (Exp (Val x))) 4 v b = case v of
  2 -> ("    [Floor]", b)
  3 -> ("    [Floor of " ++ show x ++ "]", b)
  _ -> ("    [I will round " ++ show x ++ " down to the nearest integer]", b)
nextActionExpr (UnOp Floor (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (UnOp Floor x) t v b = nextAction x t v b
nextActionExpr (UnOp Ceiling (Exp (Val x))) 4 v b = case v of
  2 -> ("    [Ceiling]", b)
  3 -> ("    [Ceiling of " ++ show x ++ "]", b)
  _ -> ("    [I will round " ++ show x ++ " up to the nearest integer]", b)
nextActionExpr (UnOp Ceiling (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (UnOp Ceiling x) t v b = nextAction x t v b
nextActionExpr (BinOp Sum (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Addition]", b)
  3 -> ("    [Addition of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will add together " ++ show x ++ " and " ++ show y ++ "]", b)
nextActionExpr (BinOp Sum (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Sum (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Sum x _) t v b = nextAction x t v b
nextActionExpr (BinOp Subtr (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Subtraction]", b)
  3 -> ("    [Subtraction of " ++ show y ++ " from " ++ show x ++ "]", b)
  _ -> ("    [I will subtract " ++ show y ++ " from " ++ show x ++ "]", b)
nextActionExpr (BinOp Subtr (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Subtr (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Subtr x _) t v b = nextAction x t v b
nextActionExpr (BinOp Product (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Product]", b)
  3 -> ("    [Product of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will multiply together " ++ show x ++ " and " ++ show y ++ "]", b)
nextActionExpr (BinOp Product (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Product (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Product x _) t v b = nextAction x t v b
nextActionExpr (BinOp Division (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Division]", b)
  3 -> ("    [Division of " ++ show x ++ " by " ++ show y ++ "]", b)
  _ -> ("    [I will divide " ++ show x ++ " by " ++ show y ++ "]", b)
nextActionExpr (BinOp Division (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Division (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Division x _) t v b = nextAction x t v b
nextActionExpr (BinOp Cons x (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Cons]", b)
  3 -> ("    [Cons of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will prepend " ++ show x ++ " to the list " ++ show y ++ "]", b)
nextActionExpr (BinOp Cons _ (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Cons _ y) t v b = nextAction y t v b
nextActionExpr (BinOp Append (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Append]", b)
  3 -> ("    [Append of " ++ show y ++ " to " ++ show x ++ "]", b)
  _ -> ("    [I will Append the list " ++ show y ++ " to the list " ++ show x ++ "]", b)
nextActionExpr (BinOp Append (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Append (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Append x _) t v b = nextAction x t v b
nextActionExpr (Case (Exp (Val x)) ys) t v b = case nextActionVal x t v b of
  ("", _) -> nextActionCase x ys t v b
  r -> r
nextActionExpr (Case x _) t v b = nextAction x t v b
nextActionExpr (BinOp And (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [And]", b)
  3 -> ("    [And of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if both " ++ show x ++ " and " ++ show y ++ " are True]", b)
nextActionExpr (BinOp And (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp And (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp And x _) t v b = nextAction x t v b
nextActionExpr (BinOp Or (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Or]", b)
  3 -> ("    [Or of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if either " ++ show x ++ " or " ++ show y ++ " are True]", b)
nextActionExpr (BinOp Or (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Or (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Or x _) t v b = nextAction x t v b
nextActionExpr (BinOp Eq (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Equality]", b)
  3 -> ("    [Equality of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " and " ++ show y ++ " are equal]", b)
nextActionExpr (BinOp Eq (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp Eq (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp Eq x _) t v b = nextAction x t v b
nextActionExpr (BinOp NEq (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Non-Equality]", b)
  3 -> ("    [Non-Equality of " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " and " ++ show y ++ " are not equal]", b)
nextActionExpr (BinOp NEq (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp NEq (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp NEq x _) t v b = nextAction x t v b
nextActionExpr (BinOp LT (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Less Than]", b)
  3 -> ("    [Less Than between " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " is less than " ++ show y ++ "]", b)
nextActionExpr (BinOp LT (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp LT (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp LT x _) t v b = nextAction x t v b
nextActionExpr (BinOp LE (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Less Than or Equal]", b)
  3 -> ("    [Less Than or Equal between " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " is less than or equal to " ++ show y ++ "]", b)
nextActionExpr (BinOp LE (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp LE (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp LE x _) t v b = nextAction x t v b
nextActionExpr (BinOp GT (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Greater Than]", b)
  3 -> ("    [Greater Than between " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " is greater than " ++ show y ++ "]", b)
nextActionExpr (BinOp GT (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp GT (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp GT x _) t v b = nextAction x t v b
nextActionExpr (BinOp GE (Exp (Val x)) (Exp (Val y))) 4 v b = case v of
  2 -> ("    [Greater Than or Equal]", b)
  3 -> ("    [Greater Than or Equal between " ++ show x ++ " and " ++ show y ++ "]", b)
  _ -> ("    [I will check if " ++ show x ++ " is greater than or equal to " ++ show y ++ "]", b)
nextActionExpr (BinOp GE (Exp (Val _)) (Exp (Val _))) _ _ _ = ("noprint", False)
nextActionExpr (BinOp GE (Exp (Val _)) y) t v b = nextAction y t v b
nextActionExpr (BinOp GE x _) t v b = nextAction x t v b

-- Determine the explanation that should be given for an expression evaluation step
-- 1st arg = evaluation step
-- 2nd arg = 'trace' flag
-- 3rd arg = 'verbosity' flag
-- 4th arg = bool to denote if we are currently inside a TRACE block
nextActionVal :: Value -> Int -> Int -> Bool -> (String, Bool)
nextActionVal (Tuple (e : es)) t v b = case nextAction e t v b of
  ("", _) -> nextActionVal (Tuple es) t v b
  x -> x
nextActionVal (List (e : es)) t v b = case nextAction e t v b of
  ("", _) -> nextActionVal (List es) t v b
  x -> x
nextActionVal (ListPattern y z) t v b = case nextAction y t v b of
  ("", _) -> nextAction z t v b
  x -> x
nextActionVal (CustomDT n (e : es) ty) t v b = case nextAction e t v b of
  ("", _) -> nextActionVal (CustomDT n es ty) t v b
  x -> x
nextActionVal _ _ _ b = ("", b)

-- Determine the explanation that should be given for a case expression evaluation step
-- 1st arg = value to replace with
-- 2nd arg = cases
-- 3rd arg = 'trace' flag
-- 4th arg = 'verbosity' flag
-- 5th arg = bool to denote if we are currently inside a TRACE block
nextActionCase :: Value -> [(Term, Term)] -> Int -> Int -> Bool -> (String, Bool)
nextActionCase _ _ 2 _ _ = ("noprint", False)
nextActionCase _ [] _ v b = case v of
  2 -> ("    [Pattern Simplification & Possible Case Selection]", b)
  3 -> ("    [Pattern Simplification & Possible Case Selection]", b)
  _ -> ("    [I will fully simplify the pattern for each case and select it if it matches]", b)
nextActionCase _ ((Exp (Var "_"), z) : _) _ v b = case v of
  2 -> ("    [Case Selection]", b)
  3 -> ("    [Case Selection of " ++ show z ++ "]", b)
  _ -> ("    [I will select the expression " ++ show z ++ " because the pattern is a wildcard ('_')]", b)
nextActionCase x ((Exp (Var y), z) : _) t v b =
  if head y `elem` ['A' .. 'Z']
    then nextActionExpr (Var y) t v b
    else case v of
      2 -> ("    [Case Selection with variable replacement]", b)
      3 -> ("    [Case Selection of " ++ show z ++ " with replacement of " ++ y ++ " with " ++ show x ++ "]", b)
      _ -> ("    [I will select the expression " ++ show z ++ " and replace all instances of " ++ y ++ " with " ++ show x ++ "]", b)
nextActionCase x ((Exp (Val y), z) : ys) t v b =
  if null toReplace
    then nextActionCase x ys t v b
    else case (toReplace, v) of
      (Just [], 2) -> ("    [Case Selection]", b)
      (Just [], 3) -> ("    [Case Selection of " ++ show z ++ "]", b)
      (Just [], _) -> ("    [I will select the expression " ++ show z ++ " because the pattern is " ++ show y ++ "]", b)
      (_, 2) -> ("    [Case Selection with variable replacement]", b)
      (Just xs, 3) -> ("    [Case Selection " ++ show z ++ " with replacement of " ++ getVars xs ++ "]", b)
      (Just xs, _) -> ("    [I will select the expression " ++ show z ++ " and replace all instances of " ++ getVars xs ++ "]", b)
      (Nothing, _) -> ("    [I will select the expression for the matching case]", b)
 where
  toReplace = fst . runWriter $ matched [] x y
  getVars [(s, r)] = "and " ++ s ++ " with " ++ show r
  getVars ((s, r) : rs) = s ++ " with " ++ show r ++ ", " ++ getVars rs
  getVars _ = "" -- Should never happen
nextActionCase _ ((y, _) : _) t v b = nextAction y t v b

{-
    DESUGARER
-}

-- Parse an entire program, returning the main expression, and the list of function references
-- 1st arg = function to evaluate (usually main)
program :: String -> Parser (Term, LUT Term)
program func = do
  _ <- lexeme ""
  as <- many $ lexeme pItemList -- lexeme removes multi-line comments
  let cs = [b ++ " " ++ unwords bs | (b, bs) <- as, b /= ""]
  case parseDecl cs of
    Left s -> customFailure s
    Right fs -> do
      let gs = foldr combine [] fs
      case toTerm gs of
        Left s -> customFailure s
        Right hs -> case getFunc hs func of
          Nothing ->
            if func == "main"
              then customFailure "Error: No main function defined\n             Every program should contain a function called 'main' which is where the program is entered, and evaluation starts"
              else customFailure $ "Error: No function " ++ func ++ " defined"
          Just e -> pure (e, hs)

-- Split up functions by their indentation (new functions begin on non-idented lines)
pItemList :: Parser (String, [String])
pItemList =
  (space1 >> pure ("", [])) <|> do
    header <- pItem False
    items <- many $ hspace1 >> pItem (not (null (indices "case" (pack header))))
    pure (header, items)

-- Take one indented line if possible, to be appended on the previous line
pItem :: Bool -> Parser String
pItem isCase = do
  x <- some $ noneOf ['\n', '\r']
  try eof <|> void eol
  if isCase && not (null (indices "->" (pack x))) && null (indices ";" (pack x)) then pure (x ++ ";") else pure x

-- parse the text into function declarations
parseDecl :: [String] -> Either String (LUT ([Term], Term))
parseDecl [] = Right []
parseDecl (c : cs) = case parse (moduleImport <|> try typeSig <|> try dataType <|> funcDecl) "" (pack c) of
  Left bundle -> Left $ unpack $ replace "input" "declaration" $ pack $ errorBundlePretty $ clean bundle
  Right [x] -> case parseDecl cs of
    Left s -> Left s
    Right xs -> Right (x : xs)
  Right y -> case parseDecl cs of
    Left s -> Left s
    Right ys -> Right (y ++ ys)

-- Throws an error if an imported module tries to import a module
moduleImport :: Parser (LUT ([Term], Term))
moduleImport = do
  lexeme "import"
  customFailure "Error: Only the module being run can import other modules in Tikka\n       This means that imported modules cannot use the 'import' keyword themselves"

-- Parse a custom datatype declaration
dataType :: Parser (LUT ([Term], Term))
dataType = do
  lexeme "data"
  n <- identifier'
  many identifier -- parses polymorphic datatypes in the form 'Maybe a = Just a | Nothing'
  lexeme "="
  c' <- typeCon
  cs <- many typeCons
  pure $ map (makeDT n) (c' : cs)
 where
  makeDT n (c, ts) = (c, (vars ts, Exp . Val $ CustomDT c (vars ts) (V n ts)))
  vars x = generateVars (length x)

-- Parses one decalaration of a type constructor
typeCon :: Parser (String, [TermType])
typeCon = do
  c <- identifier'
  xs <- many typeIdentifier
  let ts = typeReadAll 0 xs
  pure (c, ts)

-- Parses the rest of the type constructors
typeCons :: Parser (String, [TermType])
typeCons = do
  lexeme "|"
  typeCon

-- Reads in a list of types and converts it to a list of TermTypes
typeReadAll :: Int -> [String] -> [TermType]
typeReadAll _ [] = []
typeReadAll i (x : xs) = case typeRead i x of
  (N j) -> N j : typeReadAll (j + 1) xs
  t -> t : typeReadAll i xs

-- Reads in a type and converts it to an TermType
typeRead :: Int -> String -> TermType
typeRead i x
  | x == "" = error "Empty type"
  | head x `elem` ['a' .. 'z'] = N i
  | head x == '[' && last x == ']' = V "list" [typeRead i (tail $ init x)]
  | head x == '(' && last x == ')' = V "list" (map (typeRead i . trim) (splitOn "," (tail $ init x)))
  | otherwise = V x []
 where
  trim = dropWhileEnd isSpace . dropWhile isSpace

-- Disregards type signatures
typeSig :: Parser (LUT ([Term], Term))
typeSig = do
  i <- varIdentifier
  lexeme "::"
  r <- takeRest
  pure [("0typeSig", ([], Exp . Var $ i ++ " :: " ++ unpack r))]

-- Parse a function declaration/definition from Text into a name, list of arguments and a body
funcDecl :: Parser (LUT ([Term], Term))
funcDecl = do
  i <- varIdentifier
  vars <-
    many $
      choice
        [ try listPattern
        , try (Exp . Val <$> consPattern)
        , try (parens expr)
        , Exp <$> value
        , try (Exp . Var <$> identifier')
        , Exp <$> variable
        ]
  lexeme "="
  body <- expr
  lexeme $ many ";"
  eof <|> void undefinedTerm <|> do
    es <- some expr
    customFailure ("Error: The expression '" ++ show body ++ "' does not take any arguments, yet '" ++ unwords (map show es) ++ "' is applied to it\n             This means that more was found after the end of a definition (maybe there are missing brackets?)")
  pure [(i, (vars, body))]

-- Used by repl to check if a function is well-defined
isFunction :: Text -> Maybe String
isFunction t =
  if head (splitOn " " (unpack t)) == "data"
    then case parse dataType "" t of
      Left bundle -> Just (errorBundlePretty (clean bundle))
      Right _ -> Nothing
    else case parse funcDecl "" t of
      Left bundle -> Just (errorBundlePretty (clean bundle))
      Right _ -> Nothing

-- Add a function definition to a list of definitions, where those with the same name are combined
-- 1st arg = new function definition
-- 2nd arg = list of definitions
combine :: (String, ([Term], Term)) -> [(String, [([Term], Term)])] -> [(String, [([Term], Term)])]
combine ("0typeSig", _) fs = fs
combine (name, f) [] = [(name, [f])]
combine (name, f) ((name', fs) : gs) =
  if name == name'
    then (name, f : fs) : gs
    else (name', fs) : combine (name, f) gs

-- Desugars function arguments to abstractions, and creates a case statement for pattern matching where needed
toTerm :: [(String, [([Term], Term)])] -> Either String (LUT Term)
toTerm [] = Right []
toTerm ((name, cases) : fs) = case createTerm name cases of
  Left s -> Left s
  Right e -> case toTerm fs of
    Left a -> Left a
    Right b -> Right $ (name, e) : b
 where
  createTerm n cs =
    if length cs == 1
      then Right $ createAbs (head cs)
      else case checkCases cs of
        Just x -> Right x
        Nothing -> Left $ "Error: The function '" ++ n ++ "' is declared with different numbers of arguments\n       Functions can be declared multiple times (for example for pattern matching), but each declaration must have the same number of arguments / inputs. Perhaps you accidentally reused a function name?"

-- Creates an abstraction from a list of inputs and an expression
createAbs :: ([Term], Term) -> Term
createAbs ((Exp (Var s)) : es, body) = Abs s $ createAbs (es, body)
createAbs ([], body) = body
createAbs es = createPatternMatch [es]

-- Checks that each case has the same number of arguments
checkCases :: [([Term], Term)] -> Maybe Term
checkCases [] = Nothing -- Should never happen
checkCases ((args, e) : es) = if sameNumberOfArgs es (length args) then Just $ createPatternMatch ((args, e) : es) else Nothing
 where
  sameNumberOfArgs [] _ = True
  sameNumberOfArgs ((a, _) : as) n = (length a == n) && sameNumberOfArgs as n

-- Creates a case statement for pattern matching from a list of inputs
createPatternMatch :: [([Term], Term)] -> Term
createPatternMatch [] = Exp $ Var "x" -- Should never happen
createPatternMatch ((xs, x) : es) = createAbs (vars, createCases vars ((xs, x) : es))
 where
  vars = generateVars (length xs)

-- Creates the case statement with a list of variables and potential values
createCases :: [Term] -> [([Term], Term)] -> Term
createCases [var] es = Exp $ Case var [(as, a) | ([as], a) <- es]
createCases vars es = Exp $ Case (Exp $ Val $ Tuple vars) [(Exp $ Val $ Tuple as, a) | (as, a) <- es]

-- Generates a list of unique variable names, of the form 'xvar' where x is an integer
generateVars :: Int -> [Term]
generateVars 0 = []
generateVars n = Exp (Var (show n ++ "var")) : generateVars (n - 1)

-- Gets the function to be evaluated from the list of references
getFunc :: LUT Term -> String -> Maybe Term
getFunc [] _ = Nothing
getFunc ((n, x) : t) s = if n == s then Just x else getFunc t s
